openapi: "3.1.0"
info:
  title: HomeAutomationServer API
  version: 0.0.4

servers:
  - url: http://localhost:8080
    description: Local deployment of the server

paths:
  /config/automations:
    get:
      operationId: getAutomations
      responses:
        "200":
          description: A success response with all available automations.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Automation"

  /config/automations/{name}/activate:
    post:
      operationId: activateAutomation
      parameters:
        - name: name
          in: path
          description: Name of the automation
          required: true
          schema:
            type: string
      responses:
        "200":
          description: The automation was activated.

  /config/automations/{name}/deactivate:
    post:
      operationId: deactivateAutomation
      parameters:
        - name: name
          in: path
          description: Name of the automation
          required: true
          schema:
            type: string
      responses:
        "200":
          description: The automation was deactivated.

  /config/automations/{name}/stop:
    post:
      operationId: stopAutomation
      parameters:
        - name: name
          in: path
          description: Name of the automation
          required: true
          schema:
            type: string
      responses:
        "200":
          description: The currently running automation was stopped or the automation is not running.

  /pushdevices:
    post:
      operationId: registerPushDevice
      requestBody:
        description: New device to register for push notifications.
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/PushDevice"
      responses:
        "200":
          description: The device was registered for push notifications.
        "500":
          description: Some internal server error.

components:
  schemas:
    Automation:
      type: object
      properties:
        name:
          type: string
        isActive:
          type: boolean
        isRunning:
          type: boolean
      required:
        - name
        - isActive
        - isRunning

    PushDevice:
      type: object
      properties:
        deviceName:
          type: string
          description: The name of the device that created this token.
        tokenString:
          type: string
        tokenType:
          type: string
          enum: [pushNotification, liveActivityStart, liveActivityUpdate]
          description: The type of the push notification.
        activityType:
          type: string
          description: Type of the activity (e.g. WindowOpenAttributes) - only available for tokens of type "liveActivityUpdate".
      required:
        - deviceName
        - tokenString
        - tokenType
